#!/usr/bin/env python

import re
import subprocess


filename="/etc/vlanconfig"

def vlan_rem(vlan):
    cmd="ip link set "+vlan+" down"
    print subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE).stdout.read(),
    cmd="vconfig rem "+vlan
    print subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE).stdout.read(),
    pass

def vlan_up(conf):
    # parse known variables
    eth,vlanid,ip,mask=conf[:4]

    # configure interfaces
    vlan_rem("vlan"+vlanid)
    

def parse(line):
    cleanup=re.compile("#.*")
    parse=re.compile("^([^\s]*)\s*([^\s]*)\s*([^\s]*)\s*([^\s]*)\s*([^\s]*)\s*([^\s]*)\s*([^\s]*)\s*([^\s]*)\s*([^\s]*)")
    vlan_config=re.findall(parse,re.sub(cleanup,"",line))
    if vlan_config[0][0]:
        vlan_up(vlan_config[0])


with open(filename) as f:
    for line in f:
        parse(line)           

